[tool.poetry]
name = "phonebook-api"
version = "0.1.0"
description = ""
authors = ["lelandfowler <lelandplusplus@gmail.com>"]
readme = "README.md"
packages = [{include = "phonebook_api"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
